name: My first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: welcome note
              run: echo "My first githubactions job"
            - name: list files
              run: ls
            - name: Read the file
              run: cat README.md