name: Invoking shell script
on: push
jobs:
    Trigger_shell_job:
        runs-on: ubuntu-latest
        steps:
            - name:  Download the repo
              uses: actions/checkout@v4                         
            - name : list repo files
              # run: ls -altr
              run: ls -altr .github/workflows
            - name: Trigger the shell script check file
              run: | 
                   cd .github/workflows
                   chmod +x check.sh
                   ./check.sh
